import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const schemaDir = path.join(rootDir, "schemas");
const generatedDir = path.join(rootDir, "generated");
const generatedTsDir = path.join(generatedDir, "ts");
const generatedPyDir = path.join(generatedDir, "python");

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

function schemaKeyFromFile(fileName) {
  return fileName.replace(/\.schema\.json$/u, "").replace(/-/gu, "_");
}

async function main() {
  await ensureDir(generatedTsDir);
  await ensureDir(generatedPyDir);

  const schemaFiles = (await fs.readdir(schemaDir))
    .filter((file) => file.endsWith(".schema.json"))
    .sort();

  const registry = {};
  for (const fileName of schemaFiles) {
    const key = schemaKeyFromFile(fileName);
    registry[key] = `schemas/${fileName}`;
  }

  await fs.writeFile(
    path.join(generatedDir, "manifest.json"),
    JSON.stringify(registry, null, 2) + "\n",
    "utf-8"
  );

  const tsBody = [
    "// Generated by packages/shared/scripts/codegen.mjs",
    "",
    "export const schemaRegistry = {",
    ...Object.entries(registry).map(([key, relPath]) => `  ${key}: "${relPath}",`),
    "} as const;",
    "",
    "export type SchemaName = keyof typeof schemaRegistry;",
    ""
  ].join("\n");
  await fs.writeFile(path.join(generatedTsDir, "index.ts"), tsBody, "utf-8");

  const pyBody = [
    '"""Generated by packages/shared/scripts/codegen.mjs."""',
    "",
    "SCHEMA_REGISTRY = {",
    ...Object.entries(registry).map(([key, relPath]) => `    "${key}": "${relPath}",`),
    "}",
    ""
  ].join("\n");
  await fs.writeFile(path.join(generatedPyDir, "schema_registry.py"), pyBody, "utf-8");

  console.log(`Generated schema registry for ${schemaFiles.length} schema files.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
